### ISSUE TITLE
Room reservations

### ISSUE THREAD

**Issue by 253257** [zorzalo3/zorza#35]
- Zarezerwowana sala powinna być widoczna w opcji "Pokaż lekcje o danej porze"
- Brak wyświetlanego numeru lekcji przy rezerwacji sali na dole strony
- Formularz do dodawania rezerwacji sali
- Informacja o rezerwacji widoczna w planie sali

**Comment by Igifigi** [comment]
W przyszłości (po 25.08.) dodać usuwanie i wyświetlanie rezerawacji.
