### ISSUE TITLE
Show alternative periods when applicable in timetable

### ISSUE THREAD

**Issue by DietPawel** [zorzalo3/zorza#4]
![image](https://user-images.githubusercontent.com/20520161/45364936-ad9ccd80-b5db-11e8-9a1d-b4a5488c1683.png)
I think image and title is enough as description...

**Comment by wiktorkuchta** [comment]
If done, the weekdays (column headers) should be color coded like the periods. But IMO this increases the table height and clutter too much to be worth implementing. The timetable is already very dense with information

**Comment by DietPawel** [comment]
I really like idea with color coding, but I need to experiment with colors to get it working seamless with current design. On mobile I would hide periods irrelevant for particular day.

**Comment by opti0** [comment]
When lessons canceled:
![obraz](https://github.com/zorzalo3/zorza/assets/105982904/780b6356-606e-4c00-bd3d-698ffc4d401e)

**Comment by Igifigi** [comment]
closed by #69

**Comment by Igifigi** [comment]
Thanks @ZuzkaL for collaboration! If you want to continue to make changes in zorza, please fork this repo and work on your own fork. I'd be happy to assist you.
