### ISSUE TITLE
Create form for adding dayplans

### ISSUE THREAD

**Issue by opti0** [zorzalo3/zorza#67]
It will not be necessary to enter the administration panel to add a dayplan.

**Comment by ZuzkaL** [comment]
Hi @opti0 , I would love to work on this issue. Can you assign it to me? Thanks!

**Comment by opti0** [comment]
@Igifigi 
![obraz](https://github.com/zorzalo3/zorza/assets/105982904/1d0f692f-7776-4c02-981e-47ca6f2b4986)

**Comment by ZuzkaL** [comment]
If it is not working yet, I would love to do it.

**Comment by DietPawel** [comment]
@ZuzkaL It's nice to hear You would like to contribute here. Out of curiosity are You using zorza in your institution?

**Comment by ZuzkaL** [comment]
@DietPawel  Unfortunately no, my university uses its own system, but I would very much like to be involved in the development of this project, I think it is an interesting.
I know how to create components and I would be happy if I could help somehow.

**Comment by opti0** [comment]
@ZuzkaL fell free to contact me at admin@lo3.wroc.pl . I will send you an invitation to our discord server where we discuss work on the project
